services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: clms_backend
    env_file: .env
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    volumes:
      - ./back-end:/var/www/html
    command: sh -c "php artisan serve --host=0.0.0.0 --port=8000"
    networks:
      - clms_network

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    env_file: .env
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - clms_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - clms_network

  
  nginx:
    image: nginx:latest
    container_name: clms_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - clms_network

volumes:
  db_data:


networks:
  clms_network:
    driver: bridge