services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: clms_frontend
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./front-end:/app
    command: sh -c "NODE_ENV=development npm run dev"
    networks:
      - clms_network


networks:
  clms_network:
    external: true