apiVersion: v1
kind: Service
metadata:
  name: clms-backend-service
  namespace: dev
spec:
  selector:
    app: clms-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30801
  type: NodePort