apiVersion: apps/v1
kind: Deployment
metadata:
  name: clms-backend
  labels:
    app: clms-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clms-backend
  template:
    metadata:
      labels:
        app: clms-backend
    spec:
      containers:
      - name: clms-backend
        image: ${DOCKERHUB_USERNAME}/clms-backend:latest
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 20